### ISSUE TITLE
Remove background from Unity Player

### ISSUE THREAD

**Issue by Ahmadre** [snowballdigital/flutter-unity-view-widget#190]
At first: thank you sooo much for all the work and super good documentation ❤️ ❤️ ❤️  :)

Second: Let's be honest, if you're a flutter developer and want to just render an object for your main-flutter application, you'll come to the problem, where you got the ugly background in your unity-player.

Example:
<img width="536" alt="Bildschirmfoto 2020-08-13 um 13 57 44" src="https://user-images.githubusercontent.com/18512224/90131768-f97ac300-dd6c-11ea-8036-0aa7765cb737.png">

I am googling and researching over weeks to get my background transparent, so I can use my shown car without the background.

Settings I've tried:
1. Activate: **Render over Native UI** (also known as: **Preserve framebuffer alpha**)
2. Set my main Camera to: Clear Flags: **Solid Color** and the related color to: RGBA: **{0,0,0,0}** (so black-alpha!)

I also just tried to set Clear Flags to **Depth only**, but that leads to the ugly brown background.

So: what is the sense of Unity's Export Flutter function, when we cannot render our objects without a unity background? 

I would really appreciate any help :)

**Comment by TarekMedhat** [comment]
I don't know to make a transparent background in unity but I'm wondering if as you said,"you just want to render an object for your main-flutter application".
Why don't you just resize your UnityView widget instead of taking the fullscreen to just match the area you want to show your object in, with a background color same as your flutter page background color.
Something like that: the small black box showing your UnityView bounders.

![90131768-f97ac300-dd6c-11ea-8036-0aa7765cb737](https://user-images.githubusercontent.com/34374318/90136990-4367a700-dd75-11ea-8d58-753bb3014908.png)

Would that be possible?

**Comment by Ahmadre** [comment]
@TarekMedhat I already did that, but I got a complex application, where I got a Gradient background and I want to use the 3D-Model in many pages and/or Hero-Widgets. So it doesn't solve the cause problem :/. But maybe I am just a unity newbie and am missing something here?

**Comment by thomas-stockx** [comment]
Hi @Ahmadre, Unity is not really the best tool for the job for you.
There's no such thing as "removing the background", as it's very much part of a Unity environment.

It seems like you're looking for an 3D object viewer instead of a full embedded 3D game engine.
Something like [this](https://github.com/hemanthrajv/flutter_3d_obj) or [this](https://github.com/klaszlo8207/Flutter-OBJ-3D-Viewer) perhaps?

**Comment by Ahmadre** [comment]
@thomas-stockx I already tried every package you've linked ^^.

My Model can't be rendered in these packages, because of the complex materials & shaders.
If someone ever exported a full 3D-Model from unity to view it with the linkes packages from @thomas-stockx then I really would appreciate any hint for that.

**Comment by juicycleff** [comment]
@Ahmadre Actually the project that lead me to write this library had a similar request and here is how I solved this problem. I had to pass the color of my current screen as a prop to the unity game engine and changing the entire unity background dynamically and it worked like charm. No one could tell the difference between unity and flutter. Hope this helps

**Comment by juicycleff** [comment]
If this solves your issue please close it :)

**Comment by Ahmadre** [comment]
@juicycleff sounds great! Do you have any code example or reference where i can look that up? What color do I have to change and what settings do I have to set to dynamically change the color? You can also dm me if you like: rebar.ahmad@gmail.com or on twitter: @4hm4dr3

Thx :)

**Comment by Ahmadre** [comment]
Ok, solved by dynamically setting the color:

```c#
public Camera cam;

    void Start()
    {
        cam = GetComponent<Camera>();
        cam.clearFlags = CameraClearFlags.SolidColor;
    }

    void Update()
    {
    }

    public void SetBackgroundColor(string rgbString)
    {
        string[] part = rgbString.Split(',');
        Color color = new Color(float.Parse(part[0]), float.Parse(part[1]), float.Parse(part[2]));
        cam.backgroundColor = color;
    }
```

**Comment by nmfisher** [comment]
This is possible:

![image](https://user-images.githubusercontent.com/7238578/111177370-41f9a800-85fe-11eb-97c8-9bafcf44c896.png)

On 6e55f08:
1) Use Unity 2021.1.0b11 (2020.3.0f1 should also work)**
2) Ensure "Render over Native UI" is checked and your Camera Clear flags are set to Solid Color with alpha 0 BLACK (white will not work)

![image](https://user-images.githubusercontent.com/7238578/111144256-f41f7880-85da-11eb-9150-82e4dd5315d1.png)

3 Add `android:theme="@style/UnityThemeSelector.Translucent"` to the FlutterActivity element in your app/src/main/AndroidManifest.xml:
```
<activity
            android:name="io.flutter.embedding.android.FlutterActivity"
            android:launchMode="singleTop"
            **android:theme="@style/UnityThemeSelector.Translucent**"
```

* unfortunately there's a separate bug with loading native libraries in these versions of Unity, so until that's fixed, you'll need to follow the workaround @ https://github.com/juicycleff/flutter-unity-view-widget/issues/329#issuecomment-799309422


Also haven't tried on iOS yet, I think there's a separate workaround needed there too.

**Comment by kerwanp** [comment]
The solution @nmfisher provided looks obsolete.

On Unity 2020.3.32f1 even with Render over native UI checked, my background is still not transparent.

Do you have any update ?

**Comment by lxp-git** [comment]
> 



> The solution @nmfisher provided looks obsolete.
> 
> On Unity 2020.3.32f1 even with Render over native UI checked, my background is still not transparent.
> 
> Do you have any update ?

 😭We cant set background to transparent since this lib set the container background color to white by this line https://github.com/juicycleff/flutter-unity-view-widget/blob/7995993efe05de418e3af91c43bc23fc3b891232/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt#L60

**Comment by timbotimbo** [comment]
I just tested @nmfisher ’s transparency instructions on a more recent setup, and it seems to be a little easier now.


### Demo
In this video the CircularProgressIndicator is behind Unity, and the speed slider is above Unity.
This is the desired behaviour as far as I understand.

There is a black flash while Unity is launching, but I assume this is a Flutter bug. (I get the same in google maps).

https://user-images.githubusercontent.com/11444698/198906946-3dc5e226-e8af-4407-90bb-64f2e38bc5a9.mp4

### Versions
- Unity 2021.3.6f1
- Flutter 3.3.5
- flutter_unity_widget 2022.2.0
- Devices: Android 7 & 12, iPadOS 16.1


### Instructions

(iOS only needs step 1 & 2)

1. Unity Player settings: Enable 'Render over Native UI'.
2. Unity scene: Set  camera clear flags to 'Solid Color', black with alpha 0. 

(Android only from here on)

3. Make sure the android style has transparency.
I simply added transparency to the current example to remove a black background. There is probably a cleaner way to do this.

 `example/android/app/src/main/res/values/styles.xml`
```xml
        <!-- 
        ...
	This Theme is only used starting with V2 of Flutter's Android embedding. -->
 <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- <item name="android:windowBackground">@android:color/white</item> -->
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:windowIsTranslucent">true</item>
 </style>

```



4. Edit the `flutter_unity_widget` plugin: Change the white colour to transparent in `FlutterUnityWidgetController.kt` 
```
view.setBackgroundColor(Color.TRANSPARENT)   // view.setBackgroundColor(Color.WHITE)
```


5. Back to your flutter project. 
If you use `useAndroidViewSurface: false` in the `UnityWidget`, this is all that is needed.
You should now be able to replicate the video above.

6. If you need Hybrid composition (`useAndroidViewSurface: true`), you will probably need to edit the z-order in `UnityPlayerUtils.kt`. nmfisher managed to do this in the comment above.
I did not get this one fixed yet.



### Other
I did not have to adjust anything in unityLibrary/src/main/AndroidManifest.xml.
Unity seems to apply a transparent theme automatically. Which makes adding `<application android:theme="@style/UnityThemeSelector.Translucent”>` redundant.

**Comment by fiercepark** [comment]
@timbotimbo
It works on version 2021.3.15f1.
**note: I also tried this solution on unity editor 2022.x and it did not work.

**Comment by timbotimbo** [comment]
@fiercepark 
> **note: I also tried this solution on unity editor 2022.x and it did not work.

I just tried exporting with 2022.1.23f1, and got it to work following the steps above. Don't know about possible bugs in earlier versions, but it looks like it is still comaptible.

**Comment by fiercepark** [comment]
@timbotimbo

As with the other issue we covered, I am reproducing the problem on the unity-2022.2.0b16[silicon beta] of the m1 chip device.

**Comment by BranislavMateas** [comment]
Hey!

Wasn't able to make it work at first with @timbotimbo instructions at first. 

It is important to look at your styles.xml file. As it seems, in newer Flutter versions, when creating new project, there is not just one styles.xml. One is located in the 'values' directory and other one in 'values-night'.

To make this work correctly I had to delet the whole 'values-night' folder.

Not only that but also watch out for the NormalTheme. If you deleted the 'values-night' folder before, now in your 'values' directory - inside style.xml file should now see:
 `<style name="NormalTheme" parent="@android:style/Theme.Light.NoTitleBar"> `
         `    <item name="android:windowBackground">?android:colorBackground</item> `
     `</style>`
    
Rename the `parent="@android:style/Theme.Light.NoTitleBar"` to  `parent="@android:style/Theme.Black.NoTitleBar"`.
    
In my case I also renamed the LaunchTheme from Light to Black as well.

Happy coding! (and transparency 😁)

**Comment by optemoy** [comment]
Unity URP don't work it. idk how to make available camera alpha value.

**Comment by timbotimbo** [comment]
Based on a recent test:

If you want to do this with URP, you also need to disable both `post processing` and `HDR` on the camera.

**Comment by emileswain** [comment]
> Hey!
> 
> Wasn't able to make it work at first with @timbotimbo instructions at first.
> 
> It is important to look at your styles.xml file. As it seems, in newer Flutter versions, when creating new project, there is not just one styles.xml. One is located in the 'values' directory and other one in 'values-night'.
> 
> To make this work correctly I had to delete the whole 'values-night' folder.
> 
> Not only that but also watch out for the NormalTheme. If you deleted the 'values-night' folder before, now in your 'values' directory - inside style.xml file should now see: `<style name="NormalTheme" parent="@android:style/Theme.Light.NoTitleBar"> ` ` <item name="android:windowBackground">?android:colorBackground</item>` `</style>`
> 
> Rename the `parent="@android:style/Theme.Light.NoTitleBar"` to `parent="@android:style/Theme.Black.NoTitleBar"`.
> 
> In my case I also renamed the LaunchTheme from Light to Black as well.
> 
> Happy coding! (and transparency 😁)

I found that if I just applied the following to `example/android/app/src/main/res/values/styles.xml` that i would still get a black background. 
```
<item name="android:windowBackground">@android:color/transparent</item>
<item name="android:windowIsTranslucent">true</item>
```
Applying the above to the `example/android/app/src/main/res/values-night/styles.xml` as well fixed the issue.  I didn't delete the values-night folder. 

Note that i'm exporting from Unity 2022.3.22f1 with the cameras background set to black transparent. The Unity project was created using the URP demo project with the Flutter Unity package added.
