### ISSUE TITLE
ios: @interface for 'UnityAppController' declares the selector 'setUnityMessageHandler:' 

### ISSUE THREAD

**Issue by seacloud9** [snowballdigital/flutter-unity-view-widget#82]
Unity 2019.3.0f1 

Flutter Doctor outputs:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/smithb/exp/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/smithb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0
```

Error Message
```
/pub.dartlang.org/flutter_unity_widget-0.1.6+5/ios/Classes/FlutterUnityWidgetPlugin.m:96:29: 
No visible @interface for 'UnityAppController' declares the selector 'setUnityMessageHandler:'
```

**Comment by Slappiz** [comment]
We have the exact same issue on our project, if you find a solution for it I'd be glad to hear it.

**Comment by seacloud9** [comment]
I think this is a wonderful project with a copious amount of potential.  I think what makes this difficult is the fact you have 2 very fast moving targets.   The writing is on the wall though when it comes to unity as a library.  I have tried to get unity to work well with react-native and on react-native I was only able to get it to work with android.  

This is a wonderful project and it appears to me that flutter is solving many of the short comings of react-native plus it uses AOT.  So we will see.  I will keep hacking on this and any advice would be greatly appreciate thanks.

**Comment by juicycleff** [comment]
@seacloud9 are you currently using Unity and React native, then use my other library https://www.npmjs.com/package/react-native-unity-view-reinvented, it's a fork of https://www.npmjs.com/package/react-native-unity-view. For iOS use the beta version. We have a project in production using it

**Comment by juicycleff** [comment]
@seacloud9 also please make sure UnityExport classes is headers are present in the flutter-unity-view-widget pod header search path

**Comment by Slappiz** [comment]
> @seacloud9 Make sure that you have the latest version of XcodePostBuild.cs. We updated to the latest script and it works fine.

**Comment by SachinGanesh** [comment]
I was facing the same issue. I used XcodePostBuild.cs from https://github.com/juicycleff/flutter-unity-arkit-demo/blob/master/unity/ARDemoApp/Assets/Editor/XCodePostBuild.cs . It seems to fix the issue and I could build & run without any errors.

**Comment by SebastianEngel** [comment]
> I was facing the same issue. I used XcodePostBuild.cs from https://github.com/juicycleff/flutter-unity-arkit-demo/blob/master/unity/ARDemoApp/Assets/Editor/XCodePostBuild.cs . It seems to fix the issue and I could build & run without any errors.

Confirming. Thanks 👍

**Comment by juicycleff** [comment]
@seacloud9 This issue has been fixed and please look at the scripts folder, it has  been updated

**Comment by maxbhoria** [comment]
> @seacloud9 Make sure that you have the latest version of XcodePostBuild.cs. We updated to the latest script and it works fine.

i tried this solution but it did not solve my problem. Can anyone help me?

**Comment by ahahnuno** [comment]
> i tried this solution but it did not solve my problem. Can anyone help me?

Same...
