### ISSUE TITLE
IOS ERROR: "_onUnityMessage", referenced from:

### ISSUE THREAD

**Issue by rezajam** [snowballdigital/flutter-unity-view-widget#91]
I'm still having the _onUnityMessage error even though I believe it was fixed by @thomas-stockx two months ago.

Ld /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Products/Debug-iphoneos/UnityFramework.framework/UnityFramework normal arm64
cd "/Users/XXXXXXX/Desktop/unity 2/flutter-unity-view-widget-master xport/example/ios/UnityExport"
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -L/Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Products/Debug-iphoneos -L/Users/XXXXXXX/Desktop/unity\ 2/flutter-unity-view-widget-master\ xport/example/ios/UnityExport/Libraries -F/Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Products/Debug-iphoneos -filelist /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -Xlinker -no_deduplicate -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -weak_framework Metal -Xlinker -dependency_info -Xlinker /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Runner-bajlhudeslpnyrbncvmddahlibcy/Build/Products/Debug-iphoneos/UnityFramework.framework/UnityFramework

**Undefined symbols for architecture arm64:
"_onUnityMessage", referenced from:
_UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4 in Assembly-CSharp.o
(maybe you meant: _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

ANY help is greatly appreciated!

**Comment by Dimitriscs1567** [comment]
@rezajam were you able to find any solutions? I am also experiencing the same problem.

**Comment by Dimitriscs1567** [comment]
@rezajam So what actually fixed this for me is to remove the UnityFramework.framework from the Runner and added again from the Unity-iPhone. It was linked to a previous unity build.

**Comment by rezajam** [comment]
@Dimitriscs1567 I removed it but can't figure out how to add it again:| Can you explain?

**Comment by Klingens13** [comment]
I've more of a temporary solution. 
Run flutter clean.
Then Export your project once using the newest version of the XCodePostBuild.cs found in the README.md.
After that you try to compile the application, which fails.
Then you replace the XCodePostBuild.cs with [this](https://pastebin.com/X9nQkGHZ) pieced together snippet and export your unity project again.
Then you compile your project again from Xcode and it should work.
I know, not the prettiest way but it works...

**Comment by juicycleff** [comment]
@Klingens13 @rezajam Please look at the example folder, this issue has been fixed. The fix is inn the scripts folder in the library copy those files and folders to replace that existing copies you have in your unity project

**Comment by Ahmadre** [comment]
> I've more of a temporary solution.
> Run flutter clean.
> Then Export your project once using the newest version of the XCodePostBuild.cs found in the README.md.
> After that you try to compile the application, which fails.
> Then you replace the XCodePostBuild.cs with [this](https://pastebin.com/X9nQkGHZ) pieced together snippet and export your unity project again.
> Then you compile your project again from Xcode and it should work.
> I know, not the prettiest way but it works...

I don't understand your solution. Where is this "XCodePostBuild.cs" exactly?

**Comment by tomascimadorook** [comment]
> 

The error still persisting to these days, the references still broke all time, we are working with a team mate, and each time we pull the code from the server, we have to remove the package form Unity, import it again and re-export for ios, do you have any suggestion to fix this?
